### ISSUE TITLE
Detox でエミュレーター起動後、アプリが起動できない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/react-itinerary#813]
## Description
Detox でエミュレーター起動まで確認。
アプリがインストールされていないのか、起動できない。。。それともクラッシュしてるのか？？？？
![appNotReady](https://github.com/Ayato-kosaka/spelieve/assets/53715839/fb3cbd5e-2837-448c-9ba1-ac40242acc66)

```
FAIL e2e/starter.test.js (20.266 s)
  Example
    ✕ should have welcome screen (3 ms)
    ✕ should show hello screen after tap (1 ms)
    ✕ should show world screen after tap

  ● Example › should have welcome screen

    No instrumentation runner found on device emulator-5554 for package com.spelieve

      2 |   beforeAll(async () => {
      3 |     console.log("before launchApp");
    > 4 |     await device.launchApp();
        |                  ^
      5 |     console.log("after launchApp");
      6 |   });
      7 |

      at Object.launchApp (e2e/starter.test.js:4:18)

  ● Example › should show hello screen after tap

    No instrumentation runner found on device emulator-5554 for package com.spelieve

      2 |   beforeAll(async () => {
      3 |     console.log("before launchApp");
    > 4 |     await device.launchApp();
        |                  ^
      5 |     console.log("after launchApp");
      6 |   });
      7 |

      at Object.launchApp (e2e/starter.test.js:4:18)

  ● Example › should show world screen after tap

    No instrumentation runner found on device emulator-5554 for package com.spelieve

      2 |   beforeAll(async () => {
      3 |     console.log("before launchApp");
    > 4 |     await device.launchApp();
        |                  ^
      5 |     console.log("after launchApp");
      6 |   });
      7 |

      at Object.launchApp (e2e/starter.test.js:4:18)

08:45:31.144 detox[10667] E Command failed with exit code = 1:
jest --config e2e/jest.config.js
Error: Process completed with exit code 1.
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
これエラー文？

**Comment by Ayato-kosaka** [comment]
# Android Emulator を Gitpod 経由で起動して動作確認してみる
## 導入方法
Gitpodを使用して `$ANDROID_HOME/tools/bin/sdkmanager` を利用するためには、まず必要なツールをインストールして設定する必要があります。

以下にその手順を示します：

1. **Java Development Kit (JDK) のインストール**:
    Android SDKはJavaに依存しているため、JDKが必要です。OpenJDKをインストールします：

    ```bash
    sudo apt update && sudo apt install openjdk-11-jdk
    ```
    
2. **Android SDKのインストール**:
    Android SDK Command-line Toolsをダウンロードし、適切なディレクトリに解凍します：

    ```bash
    wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
    mkdir -p $HOME/Android/Sdk/cmdline-tools
    unzip commandlinetools-linux-7302050_latest.zip -d $HOME/Android/Sdk/cmdline-tools
    mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/tools
    ```
    
3. **パスの設定**:
    `sdkmanager`, `avdmanager` などのツールにパスを通します：

    ```bash
    echo 'export ANDROID_HOME=$HOME/Android/Sdk/cmdline-tools' >> ~/.bashrc
    echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> ~/.bashrc
    source ~/.bashrc
    ```

4. **Android SDKのライセンス承認**:
    Android SDKコンポーネントのライセンスを承認します：

    ```bash
    yes | sdkmanager --licenses
    ```

**Comment by Ayato-kosaka** [comment]
# GUI のエミュレーターで起動してみる
## Pixel_3a_API_30_x86 を使用
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/95f2afca-42c9-4b2f-864b-1a7e22447e74)

=> detox test 走らせるとクラッシュする、、、
[android_e2e-·-Ayato-kosaka-spelieve-e2e-dirtyfork-db9c928.webm](https://github.com/Ayato-kosaka/spelieve/assets/53715839/35a7d728-b243-4070-9e41-011efc73a2e2)

**Comment by Ayato-kosaka** [comment]
アプリをインストールしてから試したけど、変わらず、、、
同じビルドファイルをインストールして実行しても起動できるねんけどなぁ

**Comment by Ayato-kosaka** [comment]
あ、これクラッシュしてるんじゃなくて、テスト終わったから閉じてるだけかもしれない

**Comment by Ayato-kosaka** [comment]
ビルドされたapk に JUnitRunner がないのか！
````

エラーメッセージによれば、"No instrumentation runner found on device emulator-10784 for package com.spelieve"と表示されており、デバイスエミュレーターがpackage com.spelieveに対してInstrumentation Runnerを見つけられないという状況が発生しています。

DetoxはアプリをテストするためにInstrumentation APIを使用しています。そして、それを操作するためのInstrumentation Test Runnerが必要です。このエラーメッセージは、そのRunnerが見つからなかったことを示しています。
```

**Comment by Ayato-kosaka** [comment]
"gradleCommand": ":app:assembleRelease :app:assembleAndroidTest -DtestBuildType=release",
を設定するとエラーになる

**Comment by Ayato-kosaka** [comment]
@Takapy1 
このスプリントでは対応出来ないので、課題管理からは除外します。
