### ISSUE TITLE
Expo 51 へのアップデートで、EAS Build が通らない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/react-itinerary#989]
## 参考

**Comment by Ayato-kosaka** [comment]
iOS Install Pod

```

/Users/expo/.gems/arm64/gems/activesupport-7.1.3.2/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)
Did you mean?  deprecate_constant
	from /Users/expo/.gems/arm64/gems/activesupport-7.1.3.2/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby@2.7/2.7.8_1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/homebrew/Cellar/ruby@2.7/2.7.8_1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Users/expo/.gems/arm64/gems/cocoapods-1.12.0/lib/cocoapods.rb:9:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby@2.7/2.7.8_1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/homebrew/Cellar/ruby@2.7/2.7.8_1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Users/expo/.gems/arm64/gems/cocoapods-1.12.0/bin/pod:36:in `<top (required)>'
	from /Users/expo/.gems/arm64/bin/pod:25:in `load'
	from /Users/expo/.gems/arm64/bin/pod:25:in `<main>'

```

```
Internal CocoaPods error

This error is caused by a dependency issue between ActiveSupport and CocoaPods: [CocoaPods/CocoaPods#12081](https://github.com/CocoaPods/CocoaPods/issues/12081). It was fixed in cocoapods@1.14.0. If you are using a custom CocoaPods version, you can either remove it or update it to 1.14.0 or greater. [Learn more](https://docs.expo.dev/build/eas-json/#configuring-your-build-tools).
```

**Comment by Ayato-kosaka** [comment]
Android 
Run Gradle
```

Error: Unable to resolve module core-js/modules/es.string.replace.js from /home/expo/workingdir/build/node_modules/@googlemaps/url-signature/dist/index.umd.js: core-js/modules/es.string.replace.js could not be found within the project or in these directories:
  node_modules
> 1 | !function(e,r){"object"==typeof exports&&"undefined"!=typeof module?r(exports,require("core-js/modules/es.string.replace.js"),require("core-js/modules/web.dom-collections.iterator.js"),require("core-js/modules/web.url.js"),require("core-js/modules/web.url.to-json.js"),require("core-js/modules/web.url-search-params.js"),require("crypto-js/enc-base64"),require("crypto-js/hmac-sha1")):"function"==typeof define&&define.amd?define(["exports","core-js/modules/es.string.replace.js","core-js/modules/web.dom-collections.iterator.js","core-js/modules/web.url.js","core-js/modules/web.url.to-json.js","core-js/modules/web.url-search-params.js","crypto-js/enc-base64","crypto-js/hmac-sha1"],r):r((e="undefined"!=typeof globalThis?globalThis:e||self).urlSignature={},null,null,null,null,null,e.Base64,e.HmacSHA1)}(this,(function(e,r,s,o,t,n,u,l){"use strict";function c(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var a=c(u),i=c(l);function d(e,r){var s=function(e){var r=e.replace(/-/g,"+").replace(/_/g,"/");return a.default.parse(r)}(r);return i.default(e,s).toString(a.default).replace(/\+/g,"-").replace(/\//g,"_")}function j(e,r){return"string"==typeof e&&(e=new URL(e)),d("".concat(e.pathname).concat(e.search),r)}e.createSignature=j,e.createSignatureForPathAndQuery=d,e.signUrl=function(e,r){return"string"==typeof e&&(e=new URL(e)),new URL(e.toString()+"&signature="+j(e,r))},Object.defineProperty(e,"__esModule",{value:!0})}));
    |                                                                                                                                                                                                                                                                                                                                                                                                                                                           ^
  2 |
Error: Unable to resolve module core-js/modules/es.string.replace.js from /home/expo/workingdir/build/node_modules/@googlemaps/url-signature/dist/index.umd.js: core-js/modules/es.string.replace.js could not be found within the project or in these directories:
  node_modules
> 1 | !function(e,r){"object"==typeof exports&&"undefined"!=typeof module?r(exports,require("core-js/modules/es.string.replace.js"),require("core-js/modules/web.dom-collections.iterator.js"),require("core-js/modules/web.url.js"),require("core-js/modules/web.url.to-json.js"),require("core-js/modules/web.url-search-params.js"),require("crypto-js/enc-base64"),require("crypto-js/hmac-sha1")):"function"==typeof define&&define.amd?define(["exports","core-js/modules/es.string.replace.js","core-js/modules/web.dom-collections.iterator.js","core-js/modules/web.url.js","core-js/modules/web.url.to-json.js","core-js/modules/web.url-search-params.js","crypto-js/enc-base64","crypto-js/hmac-sha1"],r):r((e="undefined"!=typeof globalThis?globalThis:e||self).urlSignature={},null,null,null,null,null,e.Base64,e.HmacSHA1)}(this,(function(e,r,s,o,t,n,u,l){"use strict";function c(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var a=c(u),i=c(l);function d(e,r){var s=function(e){var r=e.replace(/-/g,"+").replace(/_/g,"/");return a.default.parse(r)}(r);return i.default(e,s).toString(a.default).replace(/\+/g,"-").replace(/\//g,"_")}function j(e,r){return"string"==typeof e&&(e=new URL(e)),d("".concat(e.pathname).concat(e.search),r)}e.createSignature=j,e.createSignatureForPathAndQuery=d,e.signUrl=function(e,r){return"string"==typeof e&&(e=new URL(e)),new URL(e.toString()+"&signature="+j(e,r))},Object.defineProperty(e,"__esModule",{value:!0})}));
    |                                                                                                                                                                                                                                                                                                                                                                                                                                                           ^
  2 |
    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 0)
    at async visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
> Task :app:createBundleReleaseJsAndAssets
FAILED
> Task :react-native-screens:configureCMakeRelWithDebInfo[arm64-v8a]
> Task :react-native-reanimated:configureCMakeRelWithDebInfo[arm64-v8a]
ASM Instrumentation process wasn't able to resolve some classes, this means that
the instrumented classes might contain corrupt stack frames. Make sure the
dependencies that contain these classes are on the runtime or the provided
classpath. Otherwise, the jvm might fail to load the corrupt classes at runtime
when running in a jvm environment like unit tests.
Classes that weren't resolved:
> com.google.common.util.concurrent.ListenableFuture
FAILURE: Build failed with an exception.
* What went wrong:


Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 7m 44s
619 actionable tasks: 619 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

```
